### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by guettli** [marazmiki/django-webdav-storage#11]
I could not find the license.

Please forgive me, if I was blind.

If you don't have one yet, please use a BSD-like license. Not GPL. 

Thank you.

**Comment by marazmiki** [comment]
Hi  Thomas,

You're completely right, license info is missed here. Basically, I release my stuff under MIT license, but since I screwed up and forgot about it, feel free use it under BSD/new BSD one :)

Also would be great if you send me a PR with the license you preferred and add yourself into AUTHORS file (it located somewhere in ``docs`` directory.
